### ISSUE TITLE
Why I can not install the  torch-points-kernels

### ISSUE THREAD

**Issue by Neverkuse** [aRI0U/RandLA-Net-pytorch#13]
Can anyone teach me how to build the environment?

**Comment by Neverkuse** [comment]
Failed building wheel for torch-points-kernels

**Comment by Thibaud-Ardoin** [comment]
Hello, 

I think it will be difficult for us to help you with that. 
I invite you to ask for some help on the concerned [project page](https://github.com/nicolas-chaulet/torch-points-kernels).

Good luck,
Thibaud

**Comment by kaimingkuang** [comment]
> Failed building wheel for torch-points-kernels

I have the same problem here. Did you fix it?

**Comment by gduthai** [comment]
i use
 from torch_points3d import knn
instand
