### ISSUE TITLE
Can you provide training methods about SemanticKITTI? SemanticKITTI's approach seems to be different :)

### ISSUE THREAD

**Issue by Zhen-ao** [aRI0U/RandLA-Net-pytorch#16]

**Comment by Thibaud-Ardoin** [comment]
Hi, thanks for you interest in the repo.

We are not planning to do this, but you are welcome to implement it and add it to the git.

Best,
Thibaud

**Comment by LeopoldACC** [comment]
If just use your model without active sampling,mIoU just get 0.24,so how to use your sampling method in KITTI dataset?
