### ISSUE TITLE
Wiil there be the supporting for SemanticKITTI?

### ISSUE THREAD

**Issue by vernon97** [aRI0U/RandLA-Net-pytorch#2]
Hi!
Thank you for your implementation of RandLA-Net in pytorch. And will there be the supproting for Semantic KITTI?

**Comment by aRI0U** [comment]
Hi!
We did not plan to support SemanticKITTI, but it should not be too hard to support it. If I remember well all you need is that your dataset is stored in 3 subdirectories called respectively train, val and test, and that your point clouds are stored in a format such that np.load(..., mmap_mode='r') works.

**Comment by vernon97** [comment]
Thank you for your reply. I'll take a try for it~

**Comment by vhchuong** [comment]
Hello @vernon97, have you succeeded in applying for the SemanticKITTI dataset?
It would be a great help if you share the code instance for that.
Thank you very much!
