### ISSUE TITLE
About warning

### ISSUE THREAD

**Issue by Alan-huazai** [aRI0U/RandLA-Net-pytorch#6]
Hello, how does the final result of your pytorch version of RandLA-Net compare with the original author's tensorflow version. Can you tell me? Thank you.

**Comment by Thibaud-Ardoin** [comment]
Hi, 
Sorry for the (VERY) late replay on this.

The only tests we did are visible here:  #11 
This project would probably need a bit more work and debug to reach the original code results. But as precised in the warning, we are not improving this git anymore. You are still welcome to include you work on this project if you have some enhancements!

Thibaud
